networks:
  sermas_dev:
    external: true

services:
  api:
    entrypoint: npm
    command: run start:debug
    networks:
      sermas_dev:
    image: ghcr.io/sermas-eu/api:dev
    build: .
    volumes:
      - ./:/app
    ports:
      - 9229:9229
