networks:
  sermas_dev:
    external: true

services:
  test-api:
    entrypoint: npm
    command: run test:watch
    networks:
      sermas_dev:
    image: ghcr.io/sermas-eu/api:dev
    build: .
    volumes:
      - ./:/app
      - ../../tmp/repository/labs/sermas-private/apps:/testapps
    ports:
      - 9229:9229
